version: '3'

services:
  backend:
    image: marwane8/backend
    container_name: "backend"
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: ${DOCKER_GATEWAY_HOST:-host.docker.internal}

  frontend:
    image: "marwane8/frontend"
    container_name: "frontend"
    ports:
        - "80:80"
    depends_on:
        - backend